### ISSUE TITLE
EXCEPTION: ReferenceError: Can't find variable: SSKeychain

### ISSUE THREAD

**Issue by ignaciolarranaga** [hamorphis/nativescript-ios-uuid#2]
Running on an emulator.
NativeScript with Angular over TypeScript.

Code:
var uuidPlugin = require("nativescript-ios-uuid");
....
	private getUUID(): string {
		if (platformModule.device.os == 'iOS') {
			return uuidPlugin.getUUID();
		} else {
			.....
		}
	}

Some suggestion ?

Full stack trace:
Jun  8 18:01:45 MacBook-Pro-de-Ignacio ordersbackoffice[66043]: CONSOLE LOG file:///app/tns_modules/@angular/core/src/facade/lang.js:370:16: getUUID@file:///app/tns_modules/nativescript-ios-uuid/index.js:3:40
	get@file:///app/shared/util/identified-http.js:16:51
	findOrSuggest@file:///app/shared/services/company.service.js:12:29
	getCompany@file:///app/pages/company/company.component.js:104:43
	ngOnInit@file:///app/pages/company/company.component.js:25:24
	detectChangesInternal
	detectChanges@file:///app/tns_modules/@angular/core/src/linker/view.js:200:35
	detectChanges@file:///app/tns_modules/@angular/core/src/linker/view.js:289:48
	detectContentChildrenChanges@file:///app/tns_modules/@angular/core/src/linker/view.js:215:50
	detectChangesInternal@file:///app/tns_modules/@angular/core/src/linker/view.js:210:42
	detectChanges@file:///app/tns_modules/@angular/core/src/linker/view.js:200:35
	detectChanges@file:///app/tns_modules/@angular/core/src/linker/view.js:289:48
	detectViewChildrenChanges@file:///app/tns_modules/@angular/core/src/linker/view.js:220:47
	detectChangesInternal
	detectChanges@file:///app/tns_modules/@angular/core/src/linker/view.js:200:35
	detectChanges@file:///app/tns_modules/@angular/core/src/linker/view.js:289:48
	detectChanges@file:///app/tns_modules/@angular/core/src/linker/view_ref.js:119:78
	forEach@[native code]
	tick@file:///app/tns_modules/@angular/core/src/application_ref.js:361:45
	file:///app/tns_modules/@angular/core/src/application_ref.js:267:129
	invoke@file:///app/tns_modules/zone.js/dist/zone-node.js:281:34
	onInvoke@file:///app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:45:47
	invoke@file:///app/tns_modules/zone.js/dist/zone-node.js:280:43
	run@file:///app/tns_modules/zone.js/dist/zone-node.js:174:50
	file:///app/tns_modules/@angular/core/src/application_ref.js:267:104
	file:///app/tns_modules/@angular/core/src/facade/async.js:123:56
	__tryOrUnsub@file:///app/tns_modules/rxjs/Subscriber.js:225:20
	next@file:///app/tns_modules/rxjs/Subscriber.js:174:34
	_next@file:///app/tns_modules/rxjs/Subscriber.js:124:30
	next@file:///app/tns_modules/rxjs/Subscriber.js:88:23
	_finalNext@file:///app/tns_modules/rxjs/Subject.js:128:34
	_next@file:///app/tns_modules/rxjs/Subject.js:120:28
	next@file:///app/tns_modules/rxjs/Subject.js:77:19
	emit@file:///app/tns_modules/@angular/core/src/facade/async.js:112:80
	_checkStable@file:///app/tns_modules/@angular/core/src/zone/ng_zone.js:141:48
	setMicrotask@file:///app/tns_modules/@angular/core/src/zone/ng_zone.js:117:35
	onHasTask@file:///app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:57:47
	hasTask@file:///app/tns_modules/zone.js/dist/zone-node.js:340:65
	_updateTaskCount@file:///app/tns_modules/zone.js/dist/zone-node.js:357:34
	invokeTask@file:///app/tns_modules/zone.js/dist/zone-node.js:318:43
	runTask@file:///app/tns_modules/zone.js/dist/zone-node.js:214:58
	drainMicroTaskQueue@file:///app/tns_modules/zone.js/dist/zone-node.js:432:43
	promiseReactionJob@[native code]
	UIApplicationMain@[native code]
	start@file:///app/tns_modules/application/application.js:233:26
	file:///app/tns_modules/nativescript-angular/application.js:81:26
	ZoneAwarePromise@file:///app/tns_modules/zone.js/dist/zone-node.js:542:38
	nativeScriptBootstrap@file:///app/tns_modules/nativescript-angular/application.js:80:23
	anonymous@file:///app/main.js:9:36
	evaluate@[native code]
	moduleEvaluation@[native code]
	[native code]
	promiseReactionJob@[native code]
Jun  8 18:01:45 MacBook-Pro-de-Ignacio ordersbackoffice[66043]: CONSOLE ERROR file:///app/tns_modules/zone.js/dist/zone-node.js:421:23: ReferenceError: Can't find variable: SSKeychain

**Comment by ignaciolarranaga** [comment]
My bad, running: "tns livesync ios --emulator --watch" but seems it does not install the pods.
Once I ran tns run ios --emulator it got fixed.

**Comment by hamorphis** [comment]
@ignaciolarranaga I released v1.0.0: https://www.npmjs.com/package/nativescript-ios-uuid. Please, give it a try and let me know if something does not work properly.
