### ISSUE TITLE
Use utils.ios.getter to read NSBundle.mainBundle and UIDevice.currentDevice

### ISSUE THREAD

**Issue by wenhsiaoyi** [hamorphis/nativescript-ios-uuid#5]
After upgrading to Nativescript 2.3.0 and Xcode 8 the following error occurs:

`TypeError: NSBundle.mainBundle is not a function. (In 'NSBundle.mainBundle()', 'NSBundle.mainBundle' is an instance of NSBundle)

**Comment by wenhsiaoyi** [comment]
I like this plugin, thank you.

function getUUID() {
    var mainBundle = utils.ios.getter(NSBundle, NSBundle.mainBundle);
    //var appName = NSBundle.mainBundle().infoDictionary.objectForKey(kCFBundleNameKey);
    var appName = mainBundle.infoDictionary.objectForKey(kCFBundleNameKey);
    var strApplicationUUID = SSKeychain.passwordForServiceAccount(appName, "incoding");
    if (!strApplicationUUID){
        var uiDevice = utils.ios.getter(UIDevice, UIDevice.currentDevice);
        //strApplicationUUID = UIDevice.currentDevice().identifierForVendor.UUIDString;
        strApplicationUUID = uiDevice.identifierForVendor.UUIDString;
        SSKeychain.setPasswordForServiceAccount(strApplicationUUID, appName, "incoding");
    }

    return strApplicationUUID;
}

**Comment by hamorphis** [comment]
@wenhsiaoyi I will fix it.

**Comment by hamorphis** [comment]
@wenhsiaoyi I released v1.0.0: https://www.npmjs.com/package/nativescript-ios-uuid. Please, give it a try and let me know if something does not work properly.
